apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.service.name | default "grafana" }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.targetPort }}
      protocol: {{ .Values.grafana.service.protocol }}
  selector:
    app: {{ .Values.grafana.service.selector.app }}
